version: "3.8"

services:
  alcobot:
    build: .
    restart: always
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - ADMIN_IDS=${ADMIN_IDS}
      - MONGO_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/alcobot?authSource=admin
      - DATABASE_NAME=alcobot

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh -u ${MONGODB_USERNAME} -p ${MONGODB_PASSWORD} --quiet || exit 1
      interval: 10s
      timeout: 10s
      retries: 5

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_PASSWORD}
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin

volumes:
  mongodb_data:

networks:
  default:
    name: alcobot_network
    driver: bridge
